
SELECT
  CAMPAIGN_ID,
  TRIM(CAMPAIGN_NAME) AS CAMPAIGN_NAME,
  INITCAP(TRIM(STATUS)) AS STATUS,
  INITCAP(TRIM(CHANNEL)) AS CHANNEL,
  START_DATE,
  END_DATE,
  --DATEDIFF(DAY, START_DATE, END_DATE) AS CAMPAIGN_DURATION_DAYS,
  INITCAP(TRIM(CAMPAIGN_TYPE)) AS CAMPAIGN_TYPE,
  INITCAP(TRIM(TARGET_AUDIENCE)) AS TARGET_AUDIENCE,
  COALESCE(BUDGET, 0) AS BUDGET

FROM {{ source('raw', 'campaigns') }}
WHERE CAMPAIGN_ID IS NOT NULL

