SELECT
  LIST_ID,
  INITCAP(TRIM(LIST_NAME)) AS LIST_NAME,
  INITCAP(TRIM(LIST_TYPE)) AS LIST_TYPE,
  TRIM(DESCRIPTION) AS DESCRIPTION,
  CREATED_DATE,
  COALESCE(SUBSCRIBER_COUNT, 0) AS SUBSCRIBER_COUNT
FROM {{ source('raw', 'email_lists') }}
WHERE LIST_ID IS NOT NULL