SELECT
  CHANNEL_ID,
  INITCAP(TRIM(CHANNEL_NAME)) AS CHANNEL_NAME,
  INITCAP(TRIM(CHANNEL_TYPE)) AS CHANNEL_TYPE,
  COALESCE(COST_PER_CHANNEL, 0) AS COST_PER_CHANNEL
FROM {{ source('raw', 'channels') }}
WHERE CHANNEL_ID IS NOT NULL