SELECT
  SUBSCRIBER_ID,
  LOWER(TRIM(EMAIL)) AS EMAIL,
  INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
  INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
  INITCAP(TRIM(GENDER)) AS GENDER,
  INITCAP(TRIM(STATUS)) AS STATUS,
  INITCAP(TRIM(COUNTRY)) AS COUNTRY,
  INITCAP(TRIM(AGE_GROUP)) AS AGE_GROUP,
  TRIM(PREFERENCES) AS PREFERENCES,
  LIST_ID,
  CAST(SUBSCRIPTION_DATE AS DATE) AS SUBSCRIPTION_DATE,
  INITCAP(TRIM(SUBSCRIPTION_SOURCE)) AS SUBSCRIPTION_SOURCE
FROM {{ source('raw', 'subscribers') }}
WHERE SUBSCRIBER_ID IS NOT NULL