SELECT
  PERFORMANCE_ID,
  --TO_DATE(DATE) AS DATE_KEY,
  DATE,
  CAMPAIGN_ID,
  COALESCE(CAST(SPEND AS DECIMAL(18,2)), 0) AS SPEND,
  COALESCE(CAST(REVENUE AS DECIMAL(18,2)), 0) AS REVENUE,
  CLICKS,
  CONVERSIONS,
  IMPRESSIONS,
  LEADS_GENERATED
  /*CASE
    WHEN COST_PER_CLICK BETWEEN 0 AND 1000 THEN CAST(COST_PER_CLICK AS DECIMAL(18,2))
    ELSE NULL
  END AS COST_PER_CLICK,
  CASE
    WHEN COST_PER_CONVERSION BETWEEN 0 AND 1000 THEN CAST(COST_PER_CONVERSION AS DECIMAL(18,2))
    ELSE NULL
  END AS COST_PER_CONVERSION */
FROM {{ source('raw', 'campaign_performance') }}
WHERE PERFORMANCE_ID IS NOT NULL