SELECT
  EMAIL_CAMPAIGN_ID,
  CAMPAIGN_ID,
  LIST_ID,
  SEND_DATE,
  TRIM(SUBJECT_LINE) AS SUBJECT_LINE,
  COALESCE(CAST(REVENUE_GENERATED AS DECIMAL(18,2)), 0) AS REVENUE_GENERATED,
  COALESCE(SENT_COUNT, 0) AS SENT_COUNT,
  COALESCE(DELIVERED_COUNT, 0) AS DELIVERED_COUNT,
  COALESCE(OPEN_COUNT, 0) AS OPEN_COUNT,
  COALESCE(CLICK_COUNT, 0) AS CLICK_COUNT,
  COALESCE(CONVERSION_COUNT, 0) AS CONVERSION_COUNT,
  COALESCE(BOUNCE_COUNT, 0) AS BOUNCE_COUNT,
  COALESCE(UNSUBSCRIBE_COUNT, 0) AS UNSUBSCRIBE_COUNT
FROM {{ source('raw', 'email_campaigns') }}
WHERE EMAIL_CAMPAIGN_ID IS NOT NULL